/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Control.ControlProducto;
import Dominio.Producto;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Citlali Orduño
 */
public class ConsultarProducto extends FrmBase {

    ControlProducto ctrlProducto;
    ArrayList<Producto> productos;
    TableRowSorter trs;
    DefaultTableModel modelo;
    int seleccionar;

    /**
     * Creates new form ConsultarProducto
     */
    public ConsultarProducto() {
        initComponents();
        this.ctrlProducto = new ControlProducto();
        this.productos = new ArrayList<>();
        this.cargarProductos();
    }

    public void cargarProductos() {
        productos = this.ctrlProducto.consultarProducto();
        if (productos != null) {
            modelo = (DefaultTableModel) tblProductos.getModel();
            modelo.setRowCount(0);
            for (Producto producto : productos) {
                String nombre = producto.getNombre();
                String categoria = producto.getCategoria().getNombre();
                float precio = producto.getPrecio();

                Object[] fila = new Object[3];
                fila[0] = nombre;
                fila[1] = categoria;
                fila[2] = precio;

                modelo.addRow(fila);

            }

        } else {
            JOptionPane.showConfirmDialog(this, "No hay productos disponibles",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    public void obtenProducto(){
         Producto prod = new Producto();
         String nombreProducto= txtBusquedaNombre.getText();
         String nom;
         if(nombreProducto.equals("")){
            nom= String.valueOf(tblProductos.getValueAt(seleccionar, 0));
           prod = this.buscarProducto(nom);
         }else{
            prod = this.buscarProducto(nombreProducto);
         }
         
        String nombre = prod.getNombre();
        String categoria= prod.getCategoria().getNombre();
        float precio= prod.getPrecio();
        
        JOptionPane.showMessageDialog(null, "Nombre: "+nombre+"\n"+"Categoria: "+categoria+"\n"+"Precio: $"+precio);
    }
    

    
    public Producto buscarProducto(String nombre){
        Producto prod = new Producto();
        ArrayList<Producto> productoPorNombre = ctrlProducto.consultarProductoPorNombre(nombre);
         for (Producto producto : productoPorNombre) {
            prod = producto;
        }
         return prod;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlCantidad1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtBusquedaNombre = new javax.swing.JTextField();
        btnDetalle = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 62)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(206, 215, 231));
        lblTitulo.setText("Consulta de productos");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 700, -1));

        pnlCantidad1.setBackground(new java.awt.Color(206, 215, 231, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa el nombre del producto a consultar:");

        txtBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaNombreActionPerformed(evt);
            }
        });
        txtBusquedaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaNombreKeyTyped(evt);
            }
        });

        btnDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetalle.setText("Detalles");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        btnMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenuPrincipal.setText("Regresar");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoría", "Precio"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        javax.swing.GroupLayout pnlCantidad1Layout = new javax.swing.GroupLayout(pnlCantidad1);
        pnlCantidad1.setLayout(pnlCantidad1Layout);
        pnlCantidad1Layout.setHorizontalGroup(
            pnlCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCantidad1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCantidad1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlCantidad1Layout.setVerticalGroup(
            pnlCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCantidad1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlCantidad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalle))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipal)
                .addGap(42, 42, 42))
        );

        getContentPane().add(pnlCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoGeneral.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, -1, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaNombreKeyTyped
        txtBusquedaNombre.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(txtBusquedaNombre.getText(), 0));
            }

        });

        trs = new TableRowSorter(modelo);
        tblProductos.setRowSorter(trs);
    }//GEN-LAST:event_txtBusquedaNombreKeyTyped

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed

        this.obtenProducto();
        
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed

        MenuAdministrarProductos jFrm = new MenuAdministrarProductos();
        jFrm.setVisible(true);
        //Ok
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:

        seleccionar = tblProductos.rowAtPoint(evt.getPoint());
        txtBusquedaNombre.setText(String.valueOf(tblProductos.getValueAt(seleccionar, 0)));
        
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCantidad1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBusquedaNombre;
    // End of variables declaration//GEN-END:variables
}
