/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Control.ControlProducto;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author R2
 */
public class MenuAdministrarVentas extends FrmBase {

    /**
     * Creates new form TomarOrden
     */
    public MenuAdministrarVentas() {
        initComponents();
        adaptarPantalla();
        
        ControlProducto ctrlProd = new ControlProducto();
        
        ctrlProd.consultarProducto();
        
//        this.resize();
    }

//    private void resize() {
//        try {
//            BufferedImage img = ImageIO.read(new File("src/Img/BannerTomarPedido.png"));
//            Image img1 = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
//            jLabel1.setIcon(new ImageIcon(img1));
//        } catch (IOException ex) {
//            Logger.getLogger(TomarOrden.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPPrincipal = new javax.swing.JPanel();
        pnlEliminarOrden = new javax.swing.JPanel();
        BnrEliminarOrden = new javax.swing.JLabel();
        iconoEliminar = new javax.swing.JLabel();
        btnEliminarOrden = new javax.swing.JButton();
        pnlTomarOrden = new javax.swing.JPanel();
        TituloMenuTomarPedido = new javax.swing.JLabel();
        IcTitulo = new javax.swing.JLabel();
        pnlModificarOrden = new javax.swing.JPanel();
        IconoModificarOrden = new javax.swing.JLabel();
        BnrEliminarOrden1 = new javax.swing.JLabel();
        iconoModifcar = new javax.swing.JLabel();
        btnModificarOrden = new javax.swing.JButton();
        BnrModificarOrden = new javax.swing.JLabel();
        pnlConsultarOrdenm = new javax.swing.JPanel();
        BnrEliminarOrden2 = new javax.swing.JLabel();
        iconoConsultar = new javax.swing.JLabel();
        btnConsultarOrden = new javax.swing.JButton();
        BackgroundFrame = new javax.swing.JLabel();
        BnrBebidasCalientes = new javax.swing.JLabel();
        btnTomasr = new javax.swing.JLabel();
        btnTomarOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEliminarOrden.setBackground(new java.awt.Color(206, 215, 231, 200));

        BnrEliminarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerOpcionEliminarOrden.png"))); // NOI18N

        iconoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónEliminarOrden.png"))); // NOI18N

        btnEliminarOrden.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnEliminarOrden.setText("Eliminar Orden");
        btnEliminarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarOrdenLayout = new javax.swing.GroupLayout(pnlEliminarOrden);
        pnlEliminarOrden.setLayout(pnlEliminarOrdenLayout);
        pnlEliminarOrdenLayout.setHorizontalGroup(
            pnlEliminarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarOrdenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoEliminar)
                .addGap(63, 63, 63))
            .addGroup(pnlEliminarOrdenLayout.createSequentialGroup()
                .addGroup(pnlEliminarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarOrdenLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BnrEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEliminarOrdenLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlEliminarOrdenLayout.setVerticalGroup(
            pnlEliminarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarOrdenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BnrEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(iconoEliminar)
                .addGap(34, 34, 34)
                .addComponent(btnEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnlTomarOrden.setBackground(new java.awt.Color(206, 215, 231, 200));

        javax.swing.GroupLayout pnlTomarOrdenLayout = new javax.swing.GroupLayout(pnlTomarOrden);
        pnlTomarOrden.setLayout(pnlTomarOrdenLayout);
        pnlTomarOrdenLayout.setHorizontalGroup(
            pnlTomarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        pnlTomarOrdenLayout.setVerticalGroup(
            pnlTomarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        TituloMenuTomarPedido.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 94)); // NOI18N
        TituloMenuTomarPedido.setForeground(new java.awt.Color(206, 215, 231));
        TituloMenuTomarPedido.setText("Tomar pedido");

        IcTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoTituloMenuAdministrarVenta.png"))); // NOI18N

        pnlModificarOrden.setBackground(new java.awt.Color(206, 215, 231, 95));

        BnrEliminarOrden1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerModificarOrden.png"))); // NOI18N

        iconoModifcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónModificarOrden.png"))); // NOI18N

        btnModificarOrden.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnModificarOrden.setText("Modificar orden");
        btnModificarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModificarOrdenLayout = new javax.swing.GroupLayout(pnlModificarOrden);
        pnlModificarOrden.setLayout(pnlModificarOrdenLayout);
        pnlModificarOrdenLayout.setHorizontalGroup(
            pnlModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarOrdenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BnrEliminarOrden1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarOrdenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarOrdenLayout.createSequentialGroup()
                        .addComponent(IconoModificarOrden)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarOrdenLayout.createSequentialGroup()
                        .addComponent(iconoModifcar)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarOrdenLayout.createSequentialGroup()
                        .addComponent(btnModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        pnlModificarOrdenLayout.setVerticalGroup(
            pnlModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarOrdenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BnrEliminarOrden1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(IconoModificarOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoModifcar)
                .addGap(37, 37, 37)
                .addComponent(btnModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pnlConsultarOrdenm.setBackground(new java.awt.Color(206, 215, 231, 95));

        BnrEliminarOrden2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerConsultarOrden.png"))); // NOI18N

        iconoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónConsultarOrden.png"))); // NOI18N

        btnConsultarOrden.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnConsultarOrden.setText("Consultar Orden");
        btnConsultarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarOrdenmLayout = new javax.swing.GroupLayout(pnlConsultarOrdenm);
        pnlConsultarOrdenm.setLayout(pnlConsultarOrdenmLayout);
        pnlConsultarOrdenmLayout.setHorizontalGroup(
            pnlConsultarOrdenmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarOrdenmLayout.createSequentialGroup()
                .addGroup(pnlConsultarOrdenmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarOrdenmLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BnrEliminarOrden2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsultarOrdenmLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(iconoConsultar))
                    .addGroup(pnlConsultarOrdenmLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnConsultarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlConsultarOrdenmLayout.setVerticalGroup(
            pnlConsultarOrdenmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarOrdenmLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BnrEliminarOrden2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(iconoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        BackgroundFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoMenuAdministarVenta.png"))); // NOI18N

        BnrBebidasCalientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerTomarPedido.png"))); // NOI18N

        btnTomasr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónTomarOrden.png"))); // NOI18N

        btnTomarOrden.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnTomarOrden.setText("Tomar orden");
        btnTomarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPPrincipalLayout = new javax.swing.GroupLayout(JPPrincipal);
        JPPrincipal.setLayout(JPPrincipalLayout);
        JPPrincipalLayout.setHorizontalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pnlTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlConsultarOrdenm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BnrModificarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(806, Short.MAX_VALUE))
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(IcTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TituloMenuTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnTomasr)
                        .addGap(46, 46, 46)
                        .addComponent(BnrBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPPrincipalLayout.createSequentialGroup()
                    .addComponent(BackgroundFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 1998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JPPrincipalLayout.setVerticalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IcTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloMenuTomarPedido))
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTomasr))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPPrincipalLayout.createSequentialGroup()
                        .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPPrincipalLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(BnrModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPPrincipalLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnlTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlEliminarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlConsultarOrdenm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BnrBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPPrincipalLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnTomarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPrincipalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackgroundFrame)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(JPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarOrdenActionPerformed
        ModificarOrden frmMod = new ModificarOrden();
        frmMod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarOrdenActionPerformed

    private void btnEliminarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarOrdenActionPerformed
        EliminarOrden frmEli = new EliminarOrden();
        frmEli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarOrdenActionPerformed

    private void btnConsultarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOrdenActionPerformed
        ConsultarOrden frmCon = new ConsultarOrden();
        frmCon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarOrdenActionPerformed

    private void btnTomarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarOrdenActionPerformed
        Categoriasv2 frmCat = new Categoriasv2();
        frmCat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTomarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrarVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundFrame;
    private javax.swing.JLabel BnrBebidasCalientes;
    private javax.swing.JLabel BnrEliminarOrden;
    private javax.swing.JLabel BnrEliminarOrden1;
    private javax.swing.JLabel BnrEliminarOrden2;
    private javax.swing.JLabel BnrModificarOrden;
    private javax.swing.JLabel IcTitulo;
    private javax.swing.JLabel IconoModificarOrden;
    private javax.swing.JPanel JPPrincipal;
    private javax.swing.JLabel TituloMenuTomarPedido;
    private javax.swing.JButton btnConsultarOrden;
    private javax.swing.JButton btnEliminarOrden;
    private javax.swing.JButton btnModificarOrden;
    private javax.swing.JButton btnTomarOrden;
    private javax.swing.JLabel btnTomasr;
    private javax.swing.JLabel iconoConsultar;
    private javax.swing.JLabel iconoEliminar;
    private javax.swing.JLabel iconoModifcar;
    private javax.swing.JPanel pnlConsultarOrdenm;
    private javax.swing.JPanel pnlEliminarOrden;
    private javax.swing.JPanel pnlModificarOrden;
    private javax.swing.JPanel pnlTomarOrden;
    // End of variables declaration//GEN-END:variables
}
