/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Citlali Orduño
 */
public class MenuAdministrarProductos extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrarProductos
     */
    public MenuAdministrarProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloMenuTomarPedido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlregistrarProd = new javax.swing.JPanel();
        btnTomasr = new javax.swing.JLabel();
        btnRegistrarProducto = new javax.swing.JButton();
        pnlModificarProd = new javax.swing.JPanel();
        btnModificarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlEliminarProd = new javax.swing.JPanel();
        btnEliminarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlConsultarProd = new javax.swing.JPanel();
        btnConsultarProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlDisponibilidadProd = new javax.swing.JPanel();
        btnDisponibilidadProducto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TituloMenuTomarPedido.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 94)); // NOI18N
        TituloMenuTomarPedido.setForeground(new java.awt.Color(206, 215, 231));
        TituloMenuTomarPedido.setText("Productos");
        getContentPane().add(TituloMenuTomarPedido);
        TituloMenuTomarPedido.setBounds(240, 70, 480, 119);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Comidas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 40, 150, 150);

        pnlregistrarProd.setBackground(new java.awt.Color(206, 215, 231, 200));

        btnTomasr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónTomarOrden.png"))); // NOI18N

        btnRegistrarProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarProducto.setText("Registrar Producto");

        javax.swing.GroupLayout pnlregistrarProdLayout = new javax.swing.GroupLayout(pnlregistrarProd);
        pnlregistrarProd.setLayout(pnlregistrarProdLayout);
        pnlregistrarProdLayout.setHorizontalGroup(
            pnlregistrarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlregistrarProdLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlregistrarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlregistrarProdLayout.createSequentialGroup()
                        .addComponent(btnTomasr)
                        .addGap(14, 14, 14)))
                .addGap(20, 20, 20))
        );
        pnlregistrarProdLayout.setVerticalGroup(
            pnlregistrarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlregistrarProdLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btnTomasr, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarProducto)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnlregistrarProd);
        pnlregistrarProd.setBounds(30, 380, 220, 380);

        pnlModificarProd.setBackground(new java.awt.Color(206, 215, 231, 200));

        btnModificarProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificarProducto.setText("Modificar Producto");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónModificarOrden.png"))); // NOI18N

        javax.swing.GroupLayout pnlModificarProdLayout = new javax.swing.GroupLayout(pnlModificarProd);
        pnlModificarProd.setLayout(pnlModificarProdLayout);
        pnlModificarProdLayout.setHorizontalGroup(
            pnlModificarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarProdLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlModificarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarProdLayout.createSequentialGroup()
                        .addComponent(btnModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarProdLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30))))
        );
        pnlModificarProdLayout.setVerticalGroup(
            pnlModificarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarProdLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarProducto)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnlModificarProd);
        pnlModificarProd.setBounds(260, 380, 220, 380);

        pnlEliminarProd.setBackground(new java.awt.Color(206, 215, 231, 200));

        btnEliminarProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónEliminarOrden.png"))); // NOI18N

        javax.swing.GroupLayout pnlEliminarProdLayout = new javax.swing.GroupLayout(pnlEliminarProd);
        pnlEliminarProd.setLayout(pnlEliminarProdLayout);
        pnlEliminarProdLayout.setHorizontalGroup(
            pnlEliminarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarProdLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(pnlEliminarProdLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEliminarProdLayout.setVerticalGroup(
            pnlEliminarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarProdLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnlEliminarProd);
        pnlEliminarProd.setBounds(490, 380, 220, 380);

        pnlConsultarProd.setBackground(new java.awt.Color(206, 215, 231, 200));

        btnConsultarProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConsultarProducto.setText("Consultar Producto");
        btnConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProductoActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoOpciónConsultarOrden.png"))); // NOI18N

        javax.swing.GroupLayout pnlConsultarProdLayout = new javax.swing.GroupLayout(pnlConsultarProd);
        pnlConsultarProd.setLayout(pnlConsultarProdLayout);
        pnlConsultarProdLayout.setHorizontalGroup(
            pnlConsultarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarProdLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarProdLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnConsultarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlConsultarProdLayout.setVerticalGroup(
            pnlConsultarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarProdLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarProducto)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnlConsultarProd);
        pnlConsultarProd.setBounds(720, 380, 220, 380);

        pnlDisponibilidadProd.setBackground(new java.awt.Color(206, 215, 231, 200));

        btnDisponibilidadProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDisponibilidadProducto.setText("Disponibilidad ");
        btnDisponibilidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibilidadProductoActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Baguette.png"))); // NOI18N

        javax.swing.GroupLayout pnlDisponibilidadProdLayout = new javax.swing.GroupLayout(pnlDisponibilidadProd);
        pnlDisponibilidadProd.setLayout(pnlDisponibilidadProdLayout);
        pnlDisponibilidadProdLayout.setHorizontalGroup(
            pnlDisponibilidadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDisponibilidadProdLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlDisponibilidadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisponibilidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDisponibilidadProdLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)))
                .addGap(20, 20, 20))
        );
        pnlDisponibilidadProdLayout.setVerticalGroup(
            pnlDisponibilidadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDisponibilidadProdLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(btnDisponibilidadProducto)
                .addGap(93, 93, 93))
        );

        getContentPane().add(pnlDisponibilidadProd);
        pnlDisponibilidadProd.setBounds(950, 380, 220, 380);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoGeneral.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 902);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarProductoActionPerformed

    private void btnDisponibilidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisponibilidadProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloMenuTomarPedido;
    private javax.swing.JButton btnConsultarProducto;
    private javax.swing.JButton btnDisponibilidadProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JLabel btnTomasr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlConsultarProd;
    private javax.swing.JPanel pnlDisponibilidadProd;
    private javax.swing.JPanel pnlEliminarProd;
    private javax.swing.JPanel pnlModificarProd;
    private javax.swing.JPanel pnlregistrarProd;
    // End of variables declaration//GEN-END:variables
}
