/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author R2
 */
public class TomarOrden extends FrmBase {

    /**
     * Creates new form TomarOrden
     */
    public TomarOrden() {
        initComponents();
        adaptarPantalla();
//        this.resize();
    }

//    private void resize() {
//        try {
//            BufferedImage img = ImageIO.read(new File("src/Img/BannerTomarPedido.png"));
//            Image img1 = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
//            jLabel1.setIcon(new ImageIcon(img1));
//        } catch (IOException ex) {
//            Logger.getLogger(TomarOrden.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPPrincipal = new javax.swing.JPanel();
        JPComidas = new javax.swing.JPanel();
        BtnComidas = new javax.swing.JButton();
        BnrComida = new javax.swing.JLabel();
        IconoComida = new javax.swing.JLabel();
        JPDesayunos = new javax.swing.JPanel();
        BtnDesayunos = new javax.swing.JButton();
        BnrDesayunos = new javax.swing.JLabel();
        IconoDesayunos = new javax.swing.JLabel();
        JPBebidasFrias = new javax.swing.JPanel();
        BtnBebidasFrias = new javax.swing.JButton();
        BnrBebidasFrias = new javax.swing.JLabel();
        IconoBebidasFrias = new javax.swing.JLabel();
        JPBebidasCalientes = new javax.swing.JPanel();
        BtnBebidasCalientes = new javax.swing.JButton();
        BnrBebidasCalientes = new javax.swing.JLabel();
        IconoBebidasCalientes = new javax.swing.JLabel();
        JPPostres = new javax.swing.JPanel();
        BtnPostres = new javax.swing.JButton();
        BnrPostres = new javax.swing.JLabel();
        IconoPostres = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        TituloMenuTomarPedido = new javax.swing.JLabel();
        IcTitulo = new javax.swing.JLabel();
        BackgroundFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPComidas.setBackground(new java.awt.Color(206, 215, 231, 200));

        BtnComidas.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        BtnComidas.setText("Comidas");
        BtnComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComidasActionPerformed(evt);
            }
        });

        BnrComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerConsultarOrden.png"))); // NOI18N

        IconoComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Comidas.png"))); // NOI18N

        javax.swing.GroupLayout JPComidasLayout = new javax.swing.GroupLayout(JPComidas);
        JPComidas.setLayout(JPComidasLayout);
        JPComidasLayout.setHorizontalGroup(
            JPComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPComidasLayout.createSequentialGroup()
                        .addComponent(BnrComida, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPComidasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(IconoComida)
                        .addGap(42, 42, 42))
                    .addGroup(JPComidasLayout.createSequentialGroup()
                        .addComponent(BtnComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JPComidasLayout.setVerticalGroup(
            JPComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnrComida, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(IconoComida)
                .addGap(18, 18, 18)
                .addComponent(BtnComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        JPDesayunos.setBackground(new java.awt.Color(206, 215, 231, 200));

        BtnDesayunos.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        BtnDesayunos.setText("Desayunos");
        BtnDesayunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesayunosActionPerformed(evt);
            }
        });

        BnrDesayunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerModificarOrden.png"))); // NOI18N

        IconoDesayunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Desayunos.png"))); // NOI18N

        javax.swing.GroupLayout JPDesayunosLayout = new javax.swing.GroupLayout(JPDesayunos);
        JPDesayunos.setLayout(JPDesayunosLayout);
        JPDesayunosLayout.setHorizontalGroup(
            JPDesayunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDesayunosLayout.createSequentialGroup()
                .addGroup(JPDesayunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPDesayunosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPDesayunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BnrDesayunos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDesayunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JPDesayunosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(IconoDesayunos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPDesayunosLayout.setVerticalGroup(
            JPDesayunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDesayunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnrDesayunos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(IconoDesayunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDesayunos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        JPBebidasFrias.setBackground(new java.awt.Color(206, 215, 231, 200));

        BtnBebidasFrias.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        BtnBebidasFrias.setText("Bebidas frías");
        BtnBebidasFrias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBebidasFriasActionPerformed(evt);
            }
        });

        BnrBebidasFrias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerOpcionEliminarOrden.png"))); // NOI18N

        IconoBebidasFrias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Bebidas Frias.png"))); // NOI18N

        javax.swing.GroupLayout JPBebidasFriasLayout = new javax.swing.GroupLayout(JPBebidasFrias);
        JPBebidasFrias.setLayout(JPBebidasFriasLayout);
        JPBebidasFriasLayout.setHorizontalGroup(
            JPBebidasFriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBebidasFriasLayout.createSequentialGroup()
                .addGroup(JPBebidasFriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBebidasFriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BnrBebidasFrias, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBebidasFriasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnBebidasFrias, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBebidasFriasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconoBebidasFrias)
                .addGap(33, 33, 33))
        );
        JPBebidasFriasLayout.setVerticalGroup(
            JPBebidasFriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBebidasFriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnrBebidasFrias, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(IconoBebidasFrias)
                .addGap(18, 18, 18)
                .addComponent(BtnBebidasFrias, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        JPBebidasCalientes.setBackground(new java.awt.Color(206, 215, 231, 200));

        BtnBebidasCalientes.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        BtnBebidasCalientes.setText("Bebidas calientes");
        BtnBebidasCalientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBebidasCalientesActionPerformed(evt);
            }
        });

        BnrBebidasCalientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerTomarPedido.png"))); // NOI18N

        IconoBebidasCalientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Bebidas Calientes.png"))); // NOI18N

        javax.swing.GroupLayout JPBebidasCalientesLayout = new javax.swing.GroupLayout(JPBebidasCalientes);
        JPBebidasCalientes.setLayout(JPBebidasCalientesLayout);
        JPBebidasCalientesLayout.setHorizontalGroup(
            JPBebidasCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBebidasCalientesLayout.createSequentialGroup()
                .addGroup(JPBebidasCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBebidasCalientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPBebidasCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnBebidasCalientes, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(BnrBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(JPBebidasCalientesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(IconoBebidasCalientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBebidasCalientesLayout.setVerticalGroup(
            JPBebidasCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBebidasCalientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnrBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconoBebidasCalientes)
                .addGap(18, 18, 18)
                .addComponent(BtnBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        JPPostres.setBackground(new java.awt.Color(206, 215, 231, 200));

        BtnPostres.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 18)); // NOI18N
        BtnPostres.setText("Postres");
        BtnPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPostresActionPerformed(evt);
            }
        });

        BnrPostres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BannerOpcionPostres.png"))); // NOI18N

        IconoPostres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icono Opción Postres.png"))); // NOI18N

        javax.swing.GroupLayout JPPostresLayout = new javax.swing.GroupLayout(JPPostres);
        JPPostres.setLayout(JPPostresLayout);
        JPPostresLayout.setHorizontalGroup(
            JPPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPostresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BnrPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPostres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPostresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconoPostres)
                .addGap(34, 34, 34))
        );
        JPPostresLayout.setVerticalGroup(
            JPPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPostresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BnrPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(IconoPostres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        BtnRegresar.setBackground(new java.awt.Color(222, 143, 62, 100));
        BtnRegresar.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 24)); // NOI18N
        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        TituloMenuTomarPedido.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 94)); // NOI18N
        TituloMenuTomarPedido.setForeground(new java.awt.Color(206, 215, 231));
        TituloMenuTomarPedido.setText("Tomar pedido");

        IcTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/IconoTituloMenuAdministrarVenta.png"))); // NOI18N

        BackgroundFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoMenuAdministarVenta.png"))); // NOI18N

        javax.swing.GroupLayout JPPrincipalLayout = new javax.swing.GroupLayout(JPPrincipal);
        JPPrincipal.setLayout(JPPrincipalLayout);
        JPPrincipalLayout.setHorizontalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegresar)
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addComponent(IcTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TituloMenuTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addComponent(JPBebidasCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPBebidasFrias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPDesayunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPPostres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(750, Short.MAX_VALUE))
            .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundFrame)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JPPrincipalLayout.setVerticalGroup(
            JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPrincipalLayout.createSequentialGroup()
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(TituloMenuTomarPedido))
                    .addGroup(JPPrincipalLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(IcTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPBebidasCalientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPBebidasFrias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(JPPostres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPComidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPDesayunos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BtnRegresar)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(JPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPPrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundFrame)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(JPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnBebidasCalientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBebidasCalientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBebidasCalientesActionPerformed

    private void BtnBebidasFriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBebidasFriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBebidasFriasActionPerformed

    private void BtnDesayunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesayunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDesayunosActionPerformed

    private void BtnComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnComidasActionPerformed

    private void BtnPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPostresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPostresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TomarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TomarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TomarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TomarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TomarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundFrame;
    private javax.swing.JLabel BnrBebidasCalientes;
    private javax.swing.JLabel BnrBebidasFrias;
    private javax.swing.JLabel BnrComida;
    private javax.swing.JLabel BnrDesayunos;
    private javax.swing.JLabel BnrPostres;
    private javax.swing.JButton BtnBebidasCalientes;
    private javax.swing.JButton BtnBebidasFrias;
    private javax.swing.JButton BtnComidas;
    private javax.swing.JButton BtnDesayunos;
    private javax.swing.JButton BtnPostres;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel IcTitulo;
    private javax.swing.JLabel IconoBebidasCalientes;
    private javax.swing.JLabel IconoBebidasFrias;
    private javax.swing.JLabel IconoComida;
    private javax.swing.JLabel IconoDesayunos;
    private javax.swing.JLabel IconoPostres;
    private javax.swing.JPanel JPBebidasCalientes;
    private javax.swing.JPanel JPBebidasFrias;
    private javax.swing.JPanel JPComidas;
    private javax.swing.JPanel JPDesayunos;
    private javax.swing.JPanel JPPostres;
    private javax.swing.JPanel JPPrincipal;
    private javax.swing.JLabel TituloMenuTomarPedido;
    // End of variables declaration//GEN-END:variables
}
